package server

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
)

// Installer serves the agent binary and a generated install script from
// the control plane itself, so machine onboarding is one command:
//
//	curl -sk https://cp:8443/install.sh | FLEET_TOKEN=<token> sh
//
// The script embeds the CA fingerprint (authenticating everything after
// bootstrap) and per-arch SHA-256 checksums (authenticating the binary
// download itself). The first fetch of install.sh is the TOFU moment —
// for stricter environments, distribute the script out-of-band and
// compare fingerprints.
type Installer struct {
	BinDir        string // holds fleet-agent-linux-{amd64,arm64}
	CAFingerprint string // hex sha256 of the CA cert DER

	mu   sync.Mutex
	sums map[string]string // filename -> sha256 (computed lazily, cached)
}

var installerBinaries = []string{"fleet-agent-linux-amd64", "fleet-agent-linux-arm64"}

func (in *Installer) sum(name string) (string, error) {
	in.mu.Lock()
	defer in.mu.Unlock()
	if in.sums == nil {
		in.sums = map[string]string{}
	}
	if s, ok := in.sums[name]; ok {
		return s, nil
	}
	raw, err := os.ReadFile(filepath.Join(in.BinDir, name))
	if err != nil {
		return "", err
	}
	h := sha256.Sum256(raw)
	s := hex.EncodeToString(h[:])
	in.sums[name] = s
	return s, nil
}

func (s *AgentServer) handleDownload(w http.ResponseWriter, r *http.Request) {
	if s.Installer == nil || s.Installer.BinDir == "" {
		http.Error(w, "binary distribution not configured (start fleet-server with --binaries)", http.StatusNotFound)
		return
	}
	name := r.PathValue("name")
	ok := false
	for _, b := range installerBinaries {
		if name == b {
			ok = true
		}
	}
	if !ok {
		http.Error(w, "unknown artifact", http.StatusNotFound)
		return
	}
	w.Header().Set("Content-Type", "application/octet-stream")
	http.ServeFile(w, r, filepath.Join(s.Installer.BinDir, name))
}

func (s *AgentServer) handleInstallScript(w http.ResponseWriter, r *http.Request) {
	if s.Installer == nil || s.Installer.BinDir == "" {
		http.Error(w, "installer not configured (start fleet-server with --binaries)", http.StatusNotFound)
		return
	}
	var sums strings.Builder
	for _, b := range installerBinaries {
		sum, err := s.Installer.sum(b)
		if err != nil {
			continue // arch not provided; script errors only if that arch is requested
		}
		arch := strings.TrimPrefix(b, "fleet-agent-linux-")
		fmt.Fprintf(&sums, "SUM_%s=%s\n", arch, sum)
	}
	script := strings.NewReplacer(
		"%HOST%", r.Host,
		"%FP%", s.Installer.CAFingerprint,
		"%SUMS%", sums.String(),
	).Replace(installScript)
	w.Header().Set("Content-Type", "text/x-shellscript; charset=utf-8")
	_, _ = w.Write([]byte(script))
}

const installScript = `#!/bin/sh
# fleetcore agent installer — generated by the control plane.
# Usage: curl -sk https://%HOST%/install.sh | FLEET_TOKEN=<token> sh
# Optional env: FLEET_NAME (machine name), FLEET_METRICS (e.g. 1s),
#               FLEET_NO_SYSTEMD=1 (skip unit setup)
set -eu

SERVER="https://%HOST%"
FP="%FP%"
%SUMS%
: "${FLEET_TOKEN:?FLEET_TOKEN is required}"

case "$(uname -m)" in
  x86_64|amd64) ARCH=amd64; SUM=${SUM_amd64:-} ;;
  aarch64|arm64) ARCH=arm64; SUM=${SUM_arm64:-} ;;
  *) echo "unsupported architecture: $(uname -m)" >&2; exit 1 ;;
esac
[ -n "$SUM" ] || { echo "no binary published for $ARCH" >&2; exit 1; }

TMP=$(mktemp)
echo "downloading fleet-agent ($ARCH)..."
curl -skf "$SERVER/download/fleet-agent-linux-$ARCH" -o "$TMP"
echo "$SUM  $TMP" | sha256sum -c - >/dev/null
install -m 0755 "$TMP" /usr/local/bin/fleet-agent
rm -f "$TMP"

if [ ! -f /var/lib/fleet-agent/cert.pem ]; then
  /usr/local/bin/fleet-agent enroll --server "$SERVER" --token "$FLEET_TOKEN" \
    --fingerprint "$FP" --name "${FLEET_NAME:-$(hostname)}"
else
  echo "already enrolled; keeping existing identity"
fi

if [ -z "${FLEET_NO_SYSTEMD:-}" ] && command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
  cat > /etc/systemd/system/fleet-agent.service <<UNIT
[Unit]
Description=fleetcore agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/fleet-agent run --server $SERVER --metrics-interval ${FLEET_METRICS:-10s}
Restart=always
RestartSec=5
ProtectHome=read-only
StateDirectory=fleet-agent
MemoryMax=128M

[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload
  systemctl enable --now fleet-agent
  echo "fleet-agent installed, enrolled, and running"
else
  echo "systemd not detected; start manually with:"
  echo "  /usr/local/bin/fleet-agent run --server $SERVER --metrics-interval ${FLEET_METRICS:-10s}"
fi
`
